name: Test And Build

on:
  push:
    branches: [ "develop" ]  
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test_and_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install dependencies  
      run: pip install -r src/requirements.txt

    - name: Check linting
      working-directory: src
      run: ruff check .

    - name: Test with pytest
      working-directory: src
      run: pytest test_app.py

    - name: Build Windows executable
      run: flet pack src/app.py --name PROYECTO CI/CD-ICS 

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: "v1.0.${{ github.run_number }}"
        name: "Versión 1.0.${{ github.run_number }}"
        files: dist/MiAppFlet.exe
        body: "Lanzamiento automático de la nueva versión aprobada en producción."

    - name: Report failure to Trello
      if: failure()
      shell: bash
      run: |
        curl -X POST "https://api.trello.com/1/cards" \
          -d "idList=${{ secrets.TRELLO_ERROR_REPORT }}" \
          -d "key=${{ secrets.TRELLO_KEY }}" \
          -d "token=${{ secrets.TRELLO_TOKEN }}" \
          -d "name=Error: ${{ github.ref_name }}-${{ github.event.head_commit.message }}" \
          -d "desc=Se ha detectado un error en las pruebas. Ver detalles en el siguiente link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Move card from In Progress to Done
      if: success() && github.ref == 'refs/heads/main'
      shell: bash
      run: |
    
        CARDS=$(curl -s "https://api.trello.com/1/lists/${{ secrets.TRELLO_IN_PROGRESS }}/cards?key=${{ secrets.TRELLO_KEY }}&token=${{ secrets.TRELLO_TOKEN }}")  
            
        COMMIT_MSG="${{ github.event.head_commit.message }}"
        CARD_ID=$(echo "$CARDS" | jq -r --arg msg "$COMMIT_MSG" '.[] | select(.name | contains($msg)) | .id' | head -n 1)

        if [ ! -z "$CARD_ID" ] && [ "$CARD_ID" != "null" ]; then
          curl -X PUT "https://api.trello.com/1/cards/$CARD_ID" \
            -d "idList=${{ secrets.TRELLO_DONE }}" \
            -d "key=${{ secrets.TRELLO_KEY }}" \
            -d "token=${{ secrets.TRELLO_TOKEN }}" \
            -d "desc=Despliegue exitoso en producción. Registro de ejecución: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Tarjeta movida con éxito."
          else
            echo "No se encontró ninguna tarjeta en In Progress que coincida con el mensaje del commit."
          fi