name: Test And Build

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test_and_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"

    - name: Install dependencies  
      run: pip install -r src/requirements.txt

    - name: Check linting
      working-directory: src
      run: ruff check .

    - name: Test with pytest
      working-directory: src
      run: pytest test_app.py

    - name: Build Windows executable
      run: flet pack src/app.py --name MiAppFlet

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: "v1.0.${{ github.run_number }}"
        name: "Versión 1.0.${{ github.run_number }}"
        files: dist/MiAppFlet.exe
        body: "Lanzamiento automático de la nueva versión aprobada en producción."
